# Generated by Django 5.0.3 on 2024-03-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_anuncio_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelTable(
            name='anuncio',
            table='anuncio',
        ),
    ]
