# Generated by Django 5.0.3 on 2024-03-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anuncio_categoria_anuncio_direccion_anuncio_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='sexo',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
