# Generated by Django 5.0.3 on 2024-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_anuncio_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
