// Generated by https://quicktype.io

export interface Job {
    id_anuncio:    string;
    id_usuario:    string;
    titulo:        string;
    descripcion:   string;
    categoria:     string;
    precio:        number;
    direccion:     string;
    u_latitud:     string;
    u_longitud:     string;
    tiempo:        string;
    genero:        string;
    fecha_fin:       Date;
    fecha_creacion:  Date;
    fechaUpdate?:    Date;
    ruta:          string;
    estado:        string;
}
